### ISSUE TITLE
Simple ping pong chatbot

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#18]
* implementation should be in ts
* research potential sdks, one option is https://github.com/nostr-dev-kit/ndk
* discuss your sdk choice and plan for development with @maciejka 
* bot should respond to simple messages like: `@pingpong ping` with a reply `pong`
* provide a docker file that will run the chatbot and a local nostr relay
* hint: https://github.com/slaninas/nostr-bot can be used as a reference

**Comment by Joy-Adah** [comment]
Hi @maciejka I'll love to work on this

**Comment by maciejka** [comment]
Hey, nice to meet you. Please have a look at the description at try to estimate the time it will take you to complete the task.

**Comment by Joy-Adah** [comment]
It will take me approximately 10 working days

**Comment by maciejka** [comment]
Cool, let's start. Please discuss it with me after you research the development plan.

**Comment by maciejka** [comment]
@Joy-Adah how is it going? Do you have an implementation plan that you want to discuss?

**Comment by Joy-Adah** [comment]
Hi @maciejka it's going well. I'll send you the implementation plan in a bit. Had to weigh the pros and cons of potential sdks just so we don't run into any hitch along the way.

**Comment by Joy-Adah** [comment]
After extensive research, I decided to go with the NDK sdk because of its ease of setup, extensive features and community support.

**Development Plan**

1. Setting up of environment.
2. Importing NDK and initializing it with the relay URLs.
3. Implementing chatbot logic.
4. Subscribing to relevant Nostr events such as NIP-01 for public messages to enable the chatbot to receive and process messages.
5. Testing and error handling by setting up a local Nostr relay.
6. Deployment

**Comment by maciejka** [comment]
Hey, any progress?

**Comment by maciejka** [comment]
@Joy-Adah?

**Comment by maciejka** [comment]
This task is closed.

**Comment by devcollinss** [comment]
Oh... okay
