### ISSUE TITLE
Mobile - Refactor hooks

### ISSUE THREAD

**Issue by MSghais** [keep-starknet-strange/joyboy#83]
### OD Hack

This issue is part of ODHack 4.0:

description - https://x.com/OnlyDust_com/status/1791035111992934563
guidelines - https://onlydust.notion.site/ODHack-Common-Guidelines-Project-leads-5e21836f85ad493f9ca429770af0ad40

### Refactoring with hooks

Refactor hooks with state, callback, useEffect and useMemo if needed.
The different components that contain functions that can be transformed as a hook are here:

1. useNotes hook: (example on User details, Feed screens) 
https://github.com/keep-starknet-strange/joyboy/blob/main/JoyboyCommunity/src/modules/feed/index.tsx

2. useProfile: 
User details, implement here: https://github.com/keep-starknet-strange/joyboy/blob/main/JoyboyCommunity/src/screens/UserDetail/index.tsx
3. useAuth: https://github.com/keep-starknet-strange/joyboy/blob/main/JoyboyCommunity/src/modules/feed/index.tsx

Please battle test it before doing a PR, core functionality refactoring on the mobile side.

### Communication

https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by Ayoazeez26** [comment]
Can I work on this?

**Comment by Immanuelolivia1** [comment]
Can I work on this ?

**Comment by josephchimebuka** [comment]
I can refactor this. should I get on it @MSghais ?

**Comment by BlackStarkGoku** [comment]
Hello, still try my shot even though I am not first, I am a React software engineer, and would love to contribute to this project. I created and used my own hooks on differents projects and know that I can tackle this issue and use "state, callback, useEffect and useMemo"

**Comment by i-hunter** [comment]
Can I work on this? This is my first time working on a project on Starknet and I’d like to be given the opportunity please, thank you .

**Comment by lindsaymoralesb** [comment]
Hi! @MSghais I’m a software engineer based in Costa Rica. I’ve been working as a full stack dev for the past four years and a half, but most of my experience is with frontend and mobile development. I’m currently finding my way through the open source works.

It would be great for me to work on this task since I have a lot of previous experience working with hooks. I’ve taken a full advanced React course and it’s my most used framework, so I think I can bring a lot of experience to the team!

**Comment by princeibs** [comment]
Hi, I am a fullstack engineer and I have experience building production react native apps professionallly. I have also worked with teams in the past. I can easily tackle this issue when assigned to me. I also have vast experience writing cairo programs and building on the blockchain as well. This issue is estimated to take two working days for me

**Comment by MSghais** [comment]
> Hi, I am a fullstack engineer and I have experience building production react native apps professionally. I have also worked with teams in the past. I can easily tackle this issue when assigned to me. I also have vast experience writing cairo programs and building on the blockchain as well. I have also contributed substantially to a couple of related projects in the past. This issue is estimated to take two working days for me

Hi appreciate your comments well detailed as need @princeibs, can you hop on Telegram, please?

Also, you have comments on two issues (related perfect), let's talk and choose on what you want to build now

**Comment by vibenedict** [comment]
Hi,
